### ISSUE TITLE
Arduino 1.6.4 support

### ISSUE THREAD

**Issue by deladriere** [stevemarple/Calunium#2]
Hi Steve
any plan to add your board here : https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls ?

ps why does the Mighty has no own core and the Calunium needs one ?

Can we just have one install for all 1284P and have all variants in one place like here : https://github.com/JChristensen/mighty-1284p

thx !

**Comment by stevemarple** [comment]
I'll look into making a pull request to add the details of Calunium.

One reason calunium has its own core is because it needs an `analogInputToDigitalPin()` function to map the analogue inputs.

**Comment by deladriere** [comment]
This is marked as closed
Where can I find the board setting for the Arduino 1.6.4 ?
Thx

**Comment by majenkotech** [comment]
> One reason calunium has its own core is because it needs an analogInputToDigitalPin() function to map the analogue inputs.

Why does that make calunium special?  Other boards (including standard Arduino boards) have that "function" (actually a macro, not a function), so what is so special about the calunium core?

From what I can see from an initial diff, most of the changes are doing things that have since been done in the Arduino core.  The calunium core would now be redundant, and anyway contains out-of-date code that is lacking some of the functionality of the latest Arduino core.  Better to drop the calunium core and just focus on getting the board definitions to work 100% with the existing Arduino core.  It'd make life simpler for you, not needing to try and track changes to the Arduino core and back-port them into your core when you really don't need to.

**Comment by stevemarple** [comment]
The issue is probably better described as needing `digitalPinToAnalogPin()`, which can be seen in commit aa95f67f9c6b991a2ca9a01da585dacab9be3939. wiring_analog.c only used the `digitalPinToAnalogPin()` macro for selected architectures, ATmega644(P)/ATmega1284(P) was not one of them.

I haven't updated to the latest Arduino code for a while but looking at the Github repository it seems that issue should now be solved, see https://github.com/arduino/Arduino/commit/938351bcae71b2ede100e5da29bd8d9e313264b5

I'll try to update to a newer Arduino software version and see if needing a separate core can be avoided but it isn't a priority for me right now.

**Comment by deladriere** [comment]
Could you also add the optiboot 16 MHz version to 1.6?
thx
